/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    LoginRegisterLayout: typeof import('./src/components/LoginRegisterLayout.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    MultiStepForm: typeof import('./src/components/form/MultiStepForm.vue')['default']
    ReviewModal: typeof import('./src/components/form/ReviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateAlertFailed: typeof import('./src/components/alert/TemplateAlertFailed.vue')['default']
    TemplateAlertSuccess: typeof import('./src/components/alert/TemplateAlertSuccess.vue')['default']
    TemplateButton: typeof import('./src/components/form/TemplateButton.vue')['default']
    TemplateForm: typeof import('./src/components/form/TemplateForm.vue')['default']
    TemplateSecondContent: typeof import('./src/components/landing-page/TemplateSecondContent.vue')['default']
    TemplateSlider: typeof import('./src/components/landing-page/TemplateSlider.vue')['default']
    TemplateStrength: typeof import('./src/components/landing-page/TemplateStrength.vue')['default']
    TemplateSweetAlert: typeof import('./src/components/alert/TemplateSweetAlert.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
